### ISSUE TITLE
Forbidden characters in the coub name 

### ISSUE THREAD

**Issue by MasterPetrik** [TeeSeal/coub-dl#11]
Coub names from the site can have forbidden characters for filenames in windows, which is stops the program from creating a file in the output folder.

for example, trying to download this coub(https://coub.com/view/1c2nh4):
![image](https://user-images.githubusercontent.com/22294259/45922736-433e3400-bedd-11e8-83d5-d17d484fb6ef.png)

These characters(screenshot of renaming manually, OS automatically removed forbidden characters):
![2018-09-23_022116 win7 mastercore](https://user-images.githubusercontent.com/22294259/45922644-8f3ba980-beda-11e8-8e16-99e8341e1d1b.png)

Moreover, there are no any fail messages in the program, so it looks like everything is done, but in fact, nothing was done, and you will not know about it if you don't enable -d or check output folder in searching of the created file.

without -d no signs of any problems:
![image](https://user-images.githubusercontent.com/22294259/45922654-ef325000-beda-11e8-8d9e-82694eca31a9.png)
but no file created.
and that's why:
![2018-09-23_021617 win7 mastercore](https://user-images.githubusercontent.com/22294259/45922661-0e30e200-bedb-11e8-83da-1a9cbc01ab13.png)

So I have two suggestions:
1. Check coub names and remove forbidden characters from them, and only then use them.
2. Check of the existence of the file at the end of the process

**Comment by TeeSeal** [comment]
I had my concerns about this when implementing the `:name:` feature, haha. I just wasn't sure how it would behave cause I didn't find any examples to test on.

I published a fix in version `1.5.1`. It will remove all illegal characters from the name and pop a warning when it does so.
