### ISSUE TITLE
Download all coubs from channel?

### ISSUE THREAD

**Issue by vdzrd** [TeeSeal/coub-dl#21]
Hello! Successfully installed your great program. Am I right that the "-dl" suffix pointing to the analog of youtube-dl package? If so, will it be possible to download the whole channel with all coubs in it? It would be great because this is why I need CLI program. Thanks a lot.

**Comment by TeeSeal** [comment]
Hi @vdzrd, the `-dl` suffix is inspired by youtube-dl, but I fail to see how it relates to the ability to download all coubs on a channel 😄 

Nonetheless, it is possible to add that feature. I'll look into doing it when I get some free time.

**Comment by TeeSeal** [comment]
Hey @vdzrd, I know it's been a while but I've finally implemented what you requested. The updated package at version 1.7.2 now includes a new executable: `coub-dl-channel`. Works similarly to the `coub-dl` executable, except the input is expected to be a channel link instead, and the output must be an existing directory. All other options from modifying the coubs will be applied to all coubs. Example:

```
coub-dl-channel -i https://coub.com/past.memories -o ./past-memories-coubs --loop 3
```
This will download 3 loops of each coub on the feed of the `past.memories` channel to the `past-memories-coubs` directory.

**Comment by vdzrd** [comment]
Thanks!
