### ISSUE TITLE
error: unknown option '-C'

### ISSUE THREAD

**Issue by berezovskyi** [TeeSeal/coub-dl#25]
Examples include `-C` option but it's not present.

P.S. Thanks for a nice project!

**Comment by TeeSeal** [comment]
Hi @berezovskyi 

Thanks for pointing this out!

The `-C` option was removed long ago in:
- https://github.com/TeeSeal/coub-dl/commit/e45355971bc7f4f30dbf8ef459845a3b33abdc33
- https://github.com/TeeSeal/coub-dl/commit/cf4b6995ee193c439e78a98295192fe974533826

Mentions of it were unintentionally left in the examples. I removed them in https://github.com/TeeSeal/coub-dl/commit/f01dcdf7689ba1cdc7207ff91a24efb161a75176.
