### ISSUE TITLE
How to Download Coubs Without Watermark?

### ISSUE THREAD

**Issue by miztizm** [TeeSeal/coub-dl#29]
First, I'd like to thank you for the great tool you've developed for downloading Coubs. It works wonderfully for the most part, but I've encountered an issue regarding watermarks.

I noticed that when downloading Coubs, the resulting video files often contain a watermark. I am interested in downloading Coubs without any watermarks. Is there a specific trick or method to achieve this using the current version of coub-dl? If so, could you please provide detailed instructions on how to do it?

Thank you for your assistance!

Best regards,

**Comment by TeeSeal** [comment]
Hey @miztizm, unfortunately there's not much we can do to get rid of the watermark to my knowledge.

This watermark was not always present for coubs, it was added at some point in the past for all coubs. The coub-dl tool uses the Coub API to fetch video sources, and the watermark is present in those sources. You can test things out yourself by sending a GET request to: `https://coub.com/api/v2/coubs/<COUB_ID>`

For example:
https://coub.com/api/v2/coubs/1lk17o
(you should be able to simply open this in your browser, there's no authorization required)

Under `file_versions.html5.video` are the video sources that coub-dl uses to build your output files (the source video is without sound, coub-dl combines that with the audio). The watermarks are embedded into those sources, and it doesn't look like there's any alternative without the watermark.

At this time your best bet is to crop the coub to get rid of it (e.g. simply using the `--crop` option will crop the coub as a square, and that should get rid of the watermark for any 16:9 coubs), but that would mean having a cropped coub 😄

**Comment by miztizm** [comment]
Thank you for your detailed explanation regarding the watermark issue! I understand now that the watermark is embedded in the video sources fetched via the Coub API, and there isn't much that can be done to remove it through coub-dl.

Thanks again for your time and response;)

Best regards,
