### ISSUE TITLE
Question/suggestion: dynamic naming feature

### ISSUE THREAD

**Issue by MasterPetrik** [TeeSeal/coub-dl#5]
I haven't found any options regarding the naming of output files.

It's would be very good to make some parameter for keeping original coub name(how it named on site) in the filename. Or just keeping original coub name by default for the saved file. Is that possible to make?

Copying and pasting name from site to rename output file manually each time isn't comfortable.

And thank you for making the only one proper working coub downloader in the whole web~

**Comment by TeeSeal** [comment]
Hey,

Thanks for the suggestion. Yeah that is possible and quite easy to implement. I’ll do it when I get some free time.

**Comment by TeeSeal** [comment]
@MasterPetrik how would you expect this to work?
If there is no output specified it uses the coub title and saves as mp4?
As in `coub-dl -i https://coub.com/someid` would produce a file in the same directory as `CoubTitle.mp4`?

**Comment by MasterPetrik** [comment]
That's how it's can be organized:

- without any additional commands coub-dl downloads file in default folder, and names it as it originally named on site.
- with -o command output folder can be set, or can be set full file path (folder+name).

is it possible to make -o command able to operate with folder paths too?  
Kind of this:

`coub-dl -i https://coub.com/someid`  >>> `default_folder\coubname.mp4`
`coub-dl -i https://coub.com/someid -o C:\coubs` >>> `C:\coubs\coubname.mp4`
`coub-dl -i https://coub.com/someid -o C:\coubs\newname.mp4` >> `C:\coubs\newname.mp4`

**Comment by MasterPetrik** [comment]
> I'm thinking a better solution would be if there was some special pattern (<name>?) in the path that I would replace with the coub name.
> 
> i.e.
> coub-dl -i https://coub.com/someid -o C:\coubs\<name>.mp4 => C:\coubs\coubname.mp4
> 
> And I could still support defaults, but only for the current directory:
> Let current directory be C:\coubs\stuff
> 
> coub-dl -i https://coub.com/someid => C:\coubs\stuff\coubname.mp4
> coub-dl -i https://coub.com/someid -f gif => C:\coubs\stuff\coubname.gif

Sounds very good, please do it.

**Comment by TeeSeal** [comment]
@MasterPetrik done in #9 . Changes  published in version `1.5.0`. I went with the `:name:` pattern instead of `<name>`, because there were some complications with the former. See the readme for more info.
