### ISSUE TITLE
Sound-only download support(mp3)

### ISSUE THREAD

**Issue by MasterPetrik** [TeeSeal/coub-dl#7]
As I see, coub-dl can download video with audio(mp4), video without audio(mp4), video without audio(gif), and next logical step is to add an option to download audio without video(mp3).

Since Coub site stores video and audio separately, I guess it's would be not so hard to implement downloading audio from coub in .mp3 file(as I remember, coub site stores sound in mp3 itself too). 

It's can be usefull when you want to download only music to listen it on you computer.

**Comment by TeeSeal** [comment]
I can do that, but the process for this would be much simpler than with the video. Cause for video I have to get the video, get the audio, find the shortest one, combine the two etc.

For audio only it would be simply getting the link and slapping the file on the disk somewhere.
I think I could make a separate command that would do this. i.e.
Let current directory be `C:\`

`$ coub-dl-mp3 -i https://coub.com/someid -o C:\music\song.mp3` => `C:\music\song.mp3`
`$ coub-dl-mp3 -i https://coub.com/someid -o C:\music\<name>.mp3` => `C:\music\coubname.mp3`
`$ coub-dl-mp3 -i https://coub.com/someid` => `C:\coubname.mp3`

And I would not have to worry about all the other options I made for the regular coub downloads. About the `<name>` thing, see what I said in #8

**Comment by TeeSeal** [comment]
@MasterPetrik done in #10. Changes published in version `1.5.0`. See readme for more info on usage.
